version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media:/app/media
    ports:
      - "8000:8000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
      args:
        - VITE_API_BASE=${VITE_API_BASE}
    env_file:
      - .env
    volumes:
      - client_dist:/app/dist
    command: ["sh", "-c", "sleep infinity"]
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - backend
      - client
    ports:
      - "8080:80"
    volumes:
      - client_dist:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  db_data:
  client_dist:
  media: